apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  labels:
    component: proxy
    app: jupyterhub
spec:
  replicas: 1
  selector:
    matchLabels:
      component: proxy
      app: jupyterhub
  template:
    metadata:
      labels:
        component: proxy
        app: jupyterhub
        hub.jupyter.org/network-access-hub: "true"
        hub.jupyter.org/network-access-singleuser: "true"
    spec:
      terminationGracePeriodSeconds: 60
      {{- if .Values.proxy.nodeSelector }}
      nodeSelector: 
        jupyterproxy: {{ .Values.proxy.nodeSelector | quote }}
      {{- end }}
      containers:
        - name: chp
          image: jupyterhub/configurable-http-proxy:3.0.0
          command:
            - configurable-http-proxy
            - --ip=0.0.0.0
            - --api-ip=0.0.0.0
            - --api-port=8001
            - --default-target=http://$(HUB_SERVICE_HOST):$(HUB_SERVICE_PORT)
            - --error-target=http://$(HUB_SERVICE_HOST):$(HUB_SERVICE_PORT)/hub/error
            - --port=8000
          env:
            - name: CONFIGPROXY_AUTH_TOKEN
              value: {{ .Values.proxy.secret }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-api
spec:
  selector:
    component: proxy
    app: jupyterhub
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-public
spec:
  selector:
    component: proxy
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8000
      nodePort: {{ .Values.proxy.nodePort }}
  type: LoadBalancer
---
